### ISSUE TITLE
Errors on algorithms that use rasters as input layers

### ISSUE THREAD

**Issue by PedroVenancio** [alexbruy/processing-saga#3]
Hi Alex,

I'm getting some errors on algorithms that use rasters as input layers, both on Linux and Windows, in QGIS 3.10. For instance:

- Grid Calculator
```
An error has occurred while executing Python code: 

NameError: name 'layers' is not defined 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/gui/AlgorithmDialog.py", line 187, in runAlgorithm
    ok, msg = self.algorithm().checkParameterValues(parameters, self.context)
  File "/home/pedro/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_saga/sagaAlgorithm.py", line 157, in checkParameterValues
    layers.extend(parameters[param.name()])
NameError: name 'layers' is not defined

Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.10.0-A Coruña A Coruña, 6c816b4204 
```
- Slope, Aspect, Curvature

```
An error has occurred while executing Python code: 

AttributeError: 'str' object has no attribute 'bandCount' 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/gui/AlgorithmDialog.py", line 187, in runAlgorithm
    ok, msg = self.algorithm().checkParameterValues(parameters, self.context)
  File "/home/pedro/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_saga/sagaAlgorithm.py", line 164, in checkParameterValues
    if raster.bandCount() > 1:
AttributeError: 'str' object has no attribute 'bandCount'

Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.10.0-A Coruña A Coruña, 6c816b4204 
```

SAGA GIS Plugin v. 0.5.0 and QGIS 3.10.

Thank you very much!

**Comment by alexbruy** [comment]
Already fixed in master

**Comment by PedroVenancio** [comment]
Hi Alex, 

Do you mean QGIS master? Will the fix be backported?

Thanks!

**Comment by PedroVenancio** [comment]
Hi Alex,

I've tested in master and the issues are still there.

```
QGIS version 3.11.0-Master
QGIS code revision 23e59c36a3
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 3.1.0dev
Running against GDAL/OGR 3.1.0dev
Compiled against GEOS 3.8.0-CAPI-1.13.1
Running against GEOS 3.8.0-CAPI-1.13.1 
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
PostgreSQL Client Version 11.5
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 7.0.0
Running against PROJ Rel. 7.0.0, March 1st, 2020
OS Version Windows 10 (10.0)
This copy of QGIS writes debugging output.
```

Any hint?

**Comment by pigreco** [comment]
@alexbruy 
I also confirm, with raster it doesn't work

**Comment by RobiFag** [comment]
@alexbruy I have the same problem using raster layers. I have tried several raster functions but I always get the python error in the image
![saga_error](https://user-images.githubusercontent.com/25825472/68752860-4a099800-0604-11ea-8e80-9e889c2dc24b.png)

**Comment by pigreco** [comment]
Sorry @alexbruy 
but why do you delete messages without giving an explanation ??
